### ISSUE TITLE
Error updating the status because of different language

### ISSUE THREAD

**Issue by martiixiam** [progressivetech/net.ourpowerbase.qrcodecheckin#10]
Hello, 

I'm trying to update the status of a participant and I'm getting this error:

```
error_message: "'Asistente' is not a valid option for field role_id"
is_error: 1
```

If I change my Participant Role label from 'Asistente' to 'Attendee', then it works.

**Comment by jmcclelland** [comment]
Ah, thanks for the report - this is indeed a bug and [here's the mistake](https://github.com/progressivetech/net.ourpowerbase.qrcodecheckin/blob/7a1bcdb102788dc25860ed5afb9ba4f0aa4aba4a/api/v3/Qrcodecheckin/Checkin.php#L46). It looks like we are hard coding the english label. We should retrieve the id of the participant status with the *name* "Attended" which will be independent of any internationalization. Or we could switch to APIv4.

I don't have time to fix it now - but that would be the tweak to make to get things running.

**Comment by rubofvil** [comment]
Tested and works fine, maybe i'm missing something

Steps:
- Configure CiviCRM in Spanish
- Change the status with the API -> qrcodecheckin.checkin
- The status changed in the participant correctly 

![image](https://user-images.githubusercontent.com/2327763/125965125-4666fc72-dcdf-41f3-a6fb-8fb4d7210e60.png)

**Comment by jmcclelland** [comment]
Thanks @rubofvil for testing.

I also failed to replicate the problem. 

I changed the label for the "Attended" Participant Status to "Asistente" and I was able to update the status without error.

Then, I changed the *name* of the "Attended" Participant Status to "Asistente" and I received the error you  reported.  Since changing the name of options is generally not supported in CiviCRM, I'm going to close the issue. 

But please comment further if we are still missing something about your bug report or if you are getting an error with the latest version while only changing the label of the status field.
