### ISSUE TITLE
Tokens don't seem to work for participant badges PDF

### ISSUE THREAD

**Issue by mgaljak** [progressivetech/net.ourpowerbase.qrcodecheckin#2]
When I go to CiviEvent administration (Administer -> CiviEvent->Event Name Badge Layouts) and I use QR tokens in the badge design it turns out empty. I can turn on the default QR code (or 1d bar code) but that just takes me to the participant page, not the check-in page.

Why wouldn't this work? There aren't any errors in CiviCRM nor PHP logs, it just doesn't render the token in the resulting PDF.  Tokens work just fine with emails.

**Comment by jmcclelland** [comment]
I see that the badge page has a drop down next to the bar code checkbox and one of the options is "qr code". Unfortunately, it has nothing to do with the qrcode checkin extension. I'm not really sure what it is supposed to do. If there was a way to insert a real token into the badge (as opposed to simply selecting existing fields) I think it would work, but otherwise it might not be possible to get the qrcode from this extension into a badge.

**Comment by mgaljak** [comment]
The tokens from this extensions are indeed listed as options as all the other tokens are listed. However when selected they produce nothing.

**Comment by jmcclelland** [comment]
@Guydn I have no plans to fix it but would welcome a pull request that fixes it.

**Comment by Guydn** [comment]
I do not have technical skills. I can try to find someone to find out a solution. What would you need to fix it ?

**Comment by jmcclelland** [comment]
Someone would have to examine the code, figure out what is going wrong, and propose a change in the code that would enable it to work.
