### ISSUE TITLE
You do not have permission to access this content

### ISSUE THREAD

**Issue by themak1985** [progressivetech/net.ourpowerbase.qrcodecheckin#25]
I only seem to be able to check in myself - anyone else's QR code I scan says I do not have permission to access this event. 

I have full admin access.

If you offer paid support - I would pay for an hour of your support

**Comment by themak1985** [comment]
This is an example QR code URL - in case it helps:
https://example.org/civicrm/?civiwp=CiviCRM&amp;q=civicrm%2Fqrcodecheckin%2F57%2F7186a5dea3030594163f17016ff2929b5a2024a410d497ca29df696e1e3dea71

**Comment by jmcclelland** [comment]
I searched the CiviCRM code base for the string "You do not have permission to access this content." and the only reference I found was in the 5.28 release notes, which says in the WordPress section:

> Fixes a 'You do not have permission to access this content.' error resulting from an extra '/' in the `q=` string in the url.

So...

1. Are you running CiviCRM 5.28 or higher?
2. Is there an extra encoded slash in there?
3. Are your *WordPress* permissions set properly?

In other words, I don't think this is a bug in the QR extension code - I think something else is going on with your WordPress install. Or, it's a bug only triggered by WordPress which means I'll need help fixing it since I don't use that platform.

**Comment by themak1985** [comment]
Running CiviCRM 5.49.1
CiviCRM URLs confuse me, but using [URL decoder](https://www.url-encode-decode.com/), I don't see another slash, it translates to: https://example.org/civicrm/?civiwp=CiviCRM&q=civicrm/qrcodecheckin/57/7186a5dea3030594163f17016ff2929b5a2024a410d497ca29df696e1e3dea71

When I visit it decoded, it actually works - when I visit it as generated from QR code reader - it gives me that error.

I think I discovered that is the issue.

**Comment by themak1985** [comment]
Update: I may have fixed this my simply loading the permalinks page on wordpress - will followup to confirm if true.

**Comment by themak1985** [comment]
Was permalinks issue.

**Comment by jmcclelland** [comment]
Thanks for the follow up!
